#!/usr/bin/env python3

import time
import random
import string
import requests
import logging

from datetime import datetime as dt

CH = "http://localhost:8123"

logging.basicConfig(
    level="INFO",
    datefmt="%H:%M:%S",
    format="%(asctime)s [%(levelname)s] %(message)s"
)
logger = logging.getLogger(__name__)

def insert_into_clickhouse():
    date = dt.now().strftime("%Y-%m-%d %H:%M:%S")
    text = "".join(random.choice(string.ascii_letters) for _ in range(20))
    query = f"INSERT INTO testing.sample(Text, EventDate, ver) VALUES (\'{text}\', \'{date}\', 1);"
    url = f"{CH}/?user=default&query={query}"
    
    r = requests.post(url)
    if r.ok:
        logger.info(f"Successfully written to CH.")
    else:
        logger.error(f"Response code: {r.status_code}. Content: {r.content}")


def main():
    while True:
        try:
            insert_into_clickhouse()
        except Exception as error:
            logger.error(f"Something went wrong: {error}")
        finally:
            time.sleep(5)


if __name__ == "__main__":
    main()

