version: '3'

services:
  ch01:
    image: yandex/clickhouse-server
    container_name: ch01
    hostname: ch01
    restart: unless-stopped
    volumes:
      - /home/akimrx/zk-migration-stand/clickhouse/data:/var/lib/clickhouse
      - /home/akimrx/zk-migration-stand/clickhouse/config.xml:/etc/clickhouse-server/config.xml
      - /home/akimrx/zk-migration-stand/clickhouse/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - 8123:8123

  zoo1:
    image: zookeeper
    restart: unless-stopped
    container_name: zoo1
    hostname: zoo1
    ports:
      - 2181:2181
    volumes:
      - /home/akimrx/zk-migration-stand/zoo1/data:/data
      - /home/akimrx/zk-migration-stand/zoo1/zoo.cfg:/conf/zoo.cfg:ro

  zoo2:
    image: zookeeper
    restart: unless-stopped
    container_name: zoo2
    hostname: zoo2
    ports:
      - 2182:2181
    volumes:
      - /home/akimrx/zk-migration-stand/zoo2/zoo.cfg:/conf/zoo.cfg:ro
      - /home/akimrx/zk-migration-stand/zoo2/data:/data

  zoo3:
    image: zookeeper
    restart: unless-stopped
    container_name: zoo3
    hostname: zoo3
    ports:
      - 2183:2181
    volumes:
      - /home/akimrx/zk-migration-stand/zoo3/zoo.cfg:/conf/zoo.cfg:ro
      - /home/akimrx/zk-migration-stand/zoo3/data:/data

  zzz1:
    image: zookeeper
    restart: unless-stopped
    container_name: zzz1
    hostname: zzz1
    ports:
      - 2184:2181
    volumes:
      - /home/akimrx/zk-migration-stand/zzz1/zoo.cfg:/conf/zoo.cfg:ro
      - /home/akimrx/zk-migration-stand/zzz1/data:/data

  zzz2:
    image: zookeeper
    restart: unless-stopped
    container_name: zzz2
    hostname: zzz2
    ports:
      - 2185:2181
    volumes:
      - /home/akimrx/zk-migration-stand/zzz2/zoo.cfg:/conf/zoo.cfg:ro
      - /home/akimrx/zk-migration-stand/zzz2/data:/data

  zzz3:
    image: zookeeper
    restart: unless-stopped
    container_name: zzz3
    hostname: zzz3
    ports:
      - 2186:2181
    volumes:
      - /home/akimrx/zk-migration-stand/zzz3/zoo.cfg:/conf/zoo.cfg:ro
      - /home/akimrx/zk-migration-stand/zzz3/data:/data
