version: '3'

services:
  ch01:
    image: yandex/clickhouse-server
    restart: unless-stopped
    container_name: ch01
    hostname: ch01
    volumes:
      - ./clickhouse/ch01/data:/var/lib/clickhouse
      - ./clickhouse/ch01/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/ch01/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - 8121:8123

  ch02:
    image: yandex/clickhouse-server
    restart: unless-stopped
    container_name: ch02
    hostname: ch02
    volumes:
      - ./clickhouse/ch02/data:/var/lib/clickhouse
      - ./clickhouse/ch02/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/ch02/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - 8122:8123

  ch03:
    image: yandex/clickhouse-server
    restart: unless-stopped
    container_name: ch03
    hostname: ch03
    volumes:
      - ./clickhouse/ch03/data:/var/lib/clickhouse
      - ./clickhouse/ch03/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/ch03/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - 8123:8123

  ch04:
    image: yandex/clickhouse-server
    restart: unless-stopped
    container_name: ch04
    hostname: ch04
    volumes:
      - ./clickhouse/ch04/data:/var/lib/clickhouse
      - ./clickhouse/ch04/config.xml:/etc/clickhouse-server/config.xml
      - ./clickhouse/ch04/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - 8124:8123

  zoo1:
    image: zookeeper
    restart: unless-stopped
    container_name: zoo1
    hostname: zoo1
    ports:
      - 2181:2181
    volumes:
      - ./zookeeper/zoo1/data:/data
      - ./zookeeper/zoo1/zoo.cfg:/conf/zoo.cfg:ro

  zoo2:
    image: zookeeper
    restart: unless-stopped
    container_name: zoo2
    hostname: zoo2
    ports:
      - 2182:2181
    volumes:
      - ./zookeeper/zoo2/data:/data
      - ./zookeeper/zoo2/zoo.cfg:/conf/zoo.cfg:ro

  zoo3:
    image: zookeeper
    restart: unless-stopped
    container_name: zoo3
    hostname: zoo3
    ports:
      - 2183:2181
    volumes:
      - ./zookeeper/zoo3/data:/data
      - ./zookeeper/zoo3/zoo.cfg:/conf/zoo.cfg:ro

  zzz1:
    image: zookeeper
    restart: unless-stopped
    container_name: zzz1
    hostname: zzz1
    ports:
      - 2186:2181
    volumes:
      - ./zookeeper/zzz1/data:/data
      - ./zookeeper/zzz1/zoo.cfg:/conf/zoo.cfg:ro

  zzz2:
    image: zookeeper
    restart: unless-stopped
    container_name: zzz2
    hostname: zzz2
    ports:
      - 2187:2181
    volumes:
      - ./zookeeper/zzz2/data:/data
      - ./zookeeper/zzz2/zoo.cfg:/conf/zoo.cfg:ro

  zzz3:
    image: zookeeper
    restart: unless-stopped
    container_name: zzz3
    hostname: zzz3
    ports:
      - 2188:2181
    volumes:
      - ./zookeeper/zzz3/data:/data
      - ./zookeeper/zzz3/zoo.cfg:/conf/zoo.cfg:ro

