#!/usr/bin/env bash

set -e

ORIGINAL_ZK_CFG="zoo-original.cfg"
JOINT_ZK_CFG="zoo-joint.cfg"

ORIGINAL_CH_CFG="config-original.xml"
UPDATED_CH_CFG="config-updated.xml"


find_leader () {
    for ZK_INDEX in 1 2 3;
    do
        if $(echo srvr | nc localhost 218${ZK_INDEX} | grep -q 'leader'); then
            echo "Leader is zoo${ZK_INDEX}"
        fi
    done
}


cleanup () {
    echo "Cleanup previous stand..."
    $(docker-compose down --remove-orphans)
    $(sudo rm -rf clickhouse/data/* || true)
    $(rm -rf zoo*/data/version-2 || true)
    $(rm -rf zzz*/data/version-2 || true)
}

original_ch () {
    echo "Switching Clickhouse to original config..."
    $(rm -f clickhouse/config.xml || true)
    $(ln -s ${ORIGINAL_CH_CFG} clickhouse/config.xml)
}


updated_ch () {
    echo "Switching Clickhouse to original config..."
    $(rm -f clickhouse/config.xml || true)
    $(ln -s ${UPDATED_CH_CFG} clickhouse/config.xml)
}

original_zk () {
    echo "Switching Zookeeper configs to original..."

    for ZK_NODE in zoo1 zoo2 zoo3;
    do
        $(rm -f ${ZK_NODE}/zoo.cfg || true)
        $(ln -s ${ORIGINAL_ZK_CFG} ${ZK_NODE}/zoo.cfg);
    done

    for ZK_NODE in zzz1 zzz2;
    do
        $(rm -f ${ZK_NODE}/zoo.cfg || true)
        $(ln -s ${ORIGINAL_ZK_CFG} $ZK_NODE/zoo.cfg);
    done

    $(sed -i '1 s/.*/1/' zzz1/data/myid)
    $(sed -i '1 s/.*/2/' zzz2/data/myid)
}

joint_zk () {
    echo "Switching Zookeeper configs to joint..."

    for ZK_NODE in zoo1 zoo2 zoo3;
    do
        $(rm -f ${ZK_NODE}/zoo.cfg || true)
        $(ln -s ${JOINT_ZK_CFG} $ZK_NODE/zoo.cfg)
    done

    for ZK_NODE in zzz1 zzz2;
    do
        $(rm -f ${ZK_NODE}/zoo.cfg || true)
        $(ln -s ${JOINT_ZK_CFG} $ZK_NODE/zoo.cfg);
    done
    
    $(sed -i '1 s/.*/4/' zzz1/data/myid)
    $(sed -i '1 s/.*/5/' zzz2/data/myid)
}


prepare () {
    echo "Cleanup old data..."
    cleanup
    
    echo "Prepare stand..."
    original_zk
    original_ch
    $(mkdir -p clickhouse/data || true)
    $(docker-compose up -d)
    sleep 2

    echo "Prepare table in the Clickhouse..."
    $(pwd)/init-ch
    echo "Stand is ready!"
}


if [[ $1 == "leader" ]];
then
    find_leader
fi

if [[ $1 == "cleanup" ]];
then
    cleanup
fi

if [[ $1 == "prepare" ]];
then
    prepare
fi

if [[ $1 == "zk" && $2 == "original" ]];
then
    original_zk
fi

if [[ $1 == "zk" && $2 == "joint" ]];
then
    joint_zk
fi

if [[ $1 == "ch" && $2 == "original" ]];
then
    original_ch
fi

if [[ $1 == "ch" && $2 == "updated" ]];
then
    updated_ch
fi
